### PR TITLE
scripts: work_dir: Implement source without system_ext with target with system_ext support

### PR DESCRIPTION
**Pull request by Fede2782**
This commit completes the work_dir setup script by adding support for source devices without system_ext (like S23 FE) and target devices with system_ext (A34 5G).

Tests done: Build ends correctly without errors, unfortunately I cannot test further that's why I made it a WIP.

### CODE REVIEW

**Comment by cat658011** [comment]
most of devices from samsung not have system_ext

**Comment by JeyKul** [comment]
@cat658011 if device has a super partition it doesnt matter. the partition inside super can be created

**Comment by Fede2782** [comment]
> most of devices from samsung not have system_ext

All MTK and QCOM from Samsung have system_ext. And very likely also all 2024 exynos...

**Comment by PeterKnecht93** [comment]
> > most of devices from samsung not have system_ext
> 
> All MTK and QCOM from Samsung have system_ext. And very likely also all 2024 exynos...

system_ext aint a thing on any exynos devices yet, they still got it inside the system partition

**Comment by salvogiangri** [comment]
> This commit completes the work_dir setup script by adding support for source devices without system_ext (like S23 FE) and target devices with system_ext (A34 5G).

The point of this PR is to add support for those cases (even if there aren't any/it's not popular) where the source/port device has no system_ext partition while the target device does, regardless of the SSI used when building the ROM.

**Comment by cat658011** [comment]
Well, yes this is exynos thing

сб, 23 нояб. 2024 г., 19:23 Fede2782 ***@***.***>:

**Pull request merged**
