### PR TITLE
docs: build.md: update

### PR DESCRIPTION
**Pull request by coffee100percnt**

### CODE REVIEW

**Comment by RisenID** [comment]
what distro?

**Comment by coffee100percnt** [comment]
wsl2 ubuntu

**Review by salvogiangri — CHANGES_REQUESTED** [review]
As already explained in the guide, it is highly suggested to use [nvm](https://github.com/nvm-sh/nvm) to install Node.js in your system. Please remove "nodejs" and "nvm" from the example command.

**Review by salvogiangri — CHANGES_REQUESTED** [review]
nvm is installed via their proprietary install script, not via the package manager.

**Comment by coffee100percnt** [comment]
already changed

**Review by salvogiangri — APPROVED** [review]

**Pull request merged**
